services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"

  mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: database
      MARIADB_USER: user
    ports:
      - "3306:3306"
